djangoChannels/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('noties.urls')),
    path('admin/', admin.site.urls),
]

noties/urls.py
from django.urls import path

from noties import views as v

urlpatterns = [
    path('', v.home, name='home'),
    path('like/<post_id>/', v.like, name='like'),
]

noties/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'post {self.post}'


class Notification(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    come_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')

noties/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.http import HttpResponse
from django.shortcuts import render

from .models import Post, Notification, Like


def home(request):
    context = {}
    posts = Post.objects.all()
    context['posts'] = posts

    noties = Notification.objects.filter(to=request.user)
    context['noties'] = noties
    context['noti_count'] = noties.count()

    return render(request, 'noties/home.html', context)


def like(request, post_id):
    post = Post.objects.get(id=post_id)
    Like.objects.create(
        user=request.user,
        post=post,
    )

    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        "notification_to_"+str(post.user.id),
        {
            'type': 'send_notification',
            'message': 'You got notification',
            'post_id': post.id,
        }
    )
    return render(request, 'noties/likes.html', {'post': post})

templates/base.html
<!DOCTYPE html>
{% load static %}{% load compress %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/custom.scss' %}">
    {% endcompress %}
    <script src="{% static 'js/htmx.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">{{ request.user.username }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
            </ul>
            <span class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                  Notifications <span class="badge bg-secondary" id="noti-counter">{{ noti_count }}</span>
                </button>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" id="notification-dropdown">
                    {% include 'noties/noti/noti.html' %}
                </div>
            </span>
        </div>
    </div>
</nav>
<section class="container">
    {% block content %}

    {% endblock content %}
</section>
<script type="module" src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/reconectingWebsocket.js' %}"></script>
<script>
    const roomName = {{ request.user.id }};

    const NotificationSocket = new ReconnectingWebSocket(
    {#const NotificationSocket = new WebSocket(#}
        'ws://'
        + window.location.host
        + '/ws/notification/for/user/'
        + roomName
        + '/'
    );

    NotificationSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        //document.querySelector('#chat-log').value += (data.message + '\n');
        console.log(data);
        document.getElementById("notification-dropdown").innerHTML = "<li class='dropdown-item'>" + data.message + "</li><hr class='dropdown-divider'>" + document.getElementById("notification-dropdown").innerHTML;
        document.getElementById("noti-counter").innerHTML = parseInt(document.getElementById("noti-counter").innerHTML) + 1;
        var like = document.getElementById("like_count"+data.post_id);
        var like_count = parseInt((like.innerText))
        like.innerHTML = like_count+1

        {#console.log(like_count+1)#}
    };

    NotificationSocket.onopen = function (e) {
        console.log('Notification socket is open now');
    };

    NotificationSocket.onclose = function (e) {
        console.error('Notification socket closed unexpectedly');
    };

</script>
</body>
</html>

templates/noties/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="row mt-5">
        {% for post in posts %}
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.description }}</p>
                        <div id="like{{ post.id }}">
                            {% include 'noties/likes.html' %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/noties/likes.html
<a hx-get="/like/{{ post.id }}/" hx-target="#like{{ post.id }}" class="btn btn-primary">Lke</a>
<span><span id="like_count{{ post.id }}">{{ post.like_set.count }}</span>likes</span>

templates/noties/noti/noti.html
{% if noties %}
    {% for noty in noties %}
        <li class='dropdown-item'>You got notification</li>
        <hr class='dropdown-divider'>
    {% endfor %}
{% endif %}